# Generated by Django 5.2.8 on 2025-11-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified_at',
        ),
    ]
