# Generated by Django 5.2.8 on 2025-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
