# Generated by Django 5.2.8 on 2025-11-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='poll',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='voteapp.campaign'),
        ),
        migrations.AddField(
            model_name='poll',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='voteapp.category'),
        ),
        migrations.AddField(
            model_name='polloption',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
